# Generated by Django 6.0.7 on 2026-07-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id_film', models.SmallAutoField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=100, unique=True)),
                ('opis', models.TextField(unique=True)),
                ('datum_izdaje', models.DateField()),
                ('poster_url', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube_id', models.CharField(blank=True, max_length=20, null=True)),
                ('ocena', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('trajanje', models.SmallIntegerField(blank=True, null=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('popularnost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('posodobljeno', models.DateTimeField(blank=True, null=True)),
                ('iskanje', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'film',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilmJezik',
            fields=[
                ('pk', models.CompositePrimaryKey('id_film', 'koda_jezika', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'film_jezik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Igralec',
            fields=[
                ('id_igralca', models.SmallAutoField(primary_key=True, serialize=False)),
                ('ime', models.CharField(max_length=20)),
                ('priimek', models.CharField(max_length=20)),
                ('datum_rojstva', models.DateField(blank=True, null=True)),
                ('biografija', models.TextField(unique=True)),
                ('nagrade', models.TextField(blank=True, null=True, unique=True)),
                ('foto_url', models.CharField(blank=True, max_length=200, null=True)),
                ('rojstni_kraj', models.CharField(blank=True, max_length=50, null=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'igralec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jezik',
            fields=[
                ('koda_jezika', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('naziv_jezik', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'jezik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Narocnik',
            fields=[
                ('emso', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ime', models.CharField(max_length=20)),
                ('priimek', models.CharField(max_length=20)),
                ('datum_rojstva', models.DateField()),
                ('e_naslov', models.CharField(max_length=60, unique=True)),
                ('telefonska_st', models.CharField(max_length=9, unique=True)),
            ],
            options={
                'db_table': 'narocnik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ogled',
            fields=[
                ('id_ogleda', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('cas_ogleda', models.TimeField()),
                ('status_ogleda', models.TextField()),
                ('id_film', models.SmallIntegerField()),
                ('datum_ogleda', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ogled',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Racun',
            fields=[
                ('id_racuna', models.SmallAutoField(primary_key=True, serialize=False)),
                ('datum_zac_narocnine', models.DateField()),
            ],
            options={
                'db_table': 'racun',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resoljucija',
            fields=[
                ('id_resoljucija', models.SmallAutoField(primary_key=True, serialize=False)),
                ('format', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resoljucija',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reziser',
            fields=[
                ('id_rezisera', models.SmallAutoField(primary_key=True, serialize=False)),
                ('ime', models.CharField(max_length=20)),
                ('priimek', models.CharField(max_length=20)),
                ('datum_zac_dela', models.DateField(blank=True, null=True)),
                ('biografija', models.TextField(unique=True)),
                ('nagrade', models.TextField(blank=True, null=True, unique=True)),
                ('foto_url', models.CharField(blank=True, max_length=200, null=True)),
                ('datum_rojstva', models.DateField(blank=True, null=True)),
                ('rojstni_kraj', models.CharField(blank=True, max_length=50, null=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'reziser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vloga',
            fields=[
                ('id_vloga', models.SmallAutoField(primary_key=True, serialize=False)),
                ('vrsta_vloge', models.TextField()),
                ('lik', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'vloga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zanr',
            fields=[
                ('id_zanr', models.SmallAutoField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=20, unique=True)),
                ('opis_zanra', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'zanr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZanrFilm',
            fields=[
                ('pk', models.CompositePrimaryKey('id_film', 'id_zanr', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'zanr_film',
                'managed': False,
            },
        ),
    ]
