# Generated by Django 6.0.7 on 2026-07-19 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'managed': False, 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='filmjezik',
            options={'managed': False, 'verbose_name': 'Movie Language', 'verbose_name_plural': 'Movie Languages'},
        ),
        migrations.AlterModelOptions(
            name='igralec',
            options={'managed': False, 'verbose_name': 'Actor', 'verbose_name_plural': 'Actors'},
        ),
        migrations.AlterModelOptions(
            name='jezik',
            options={'managed': False, 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='narocnik',
            options={'managed': False, 'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
        migrations.AlterModelOptions(
            name='ogled',
            options={'managed': False, 'verbose_name': 'View', 'verbose_name_plural': 'Views'},
        ),
        migrations.AlterModelOptions(
            name='racun',
            options={'managed': False, 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='resoljucija',
            options={'managed': False, 'verbose_name': 'Resolution', 'verbose_name_plural': 'Resolutions'},
        ),
        migrations.AlterModelOptions(
            name='reziser',
            options={'managed': False, 'verbose_name': 'Director', 'verbose_name_plural': 'Directors'},
        ),
        migrations.AlterModelOptions(
            name='vloga',
            options={'managed': False, 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='zanr',
            options={'managed': False, 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='zanrfilm',
            options={'managed': False, 'verbose_name': 'Movie Genre', 'verbose_name_plural': 'Movie Genres'},
        ),
    ]
